name: daisiedex
description: "My love letter to a pretty lady."
publish_to: 'none'
version: 1.1.1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  envied: ^1.3.2
  http: ^1.6.0
  image_picker: ^1.2.1
  internet_connection_checker_plus: ^2.9.1+2
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_native_splash: ^2.4.7
  gal: ^2.3.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  envied_generator: ^1.3.2
  build_runner: ^2.10.4
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  fonts:
    - family: Zain
      fonts:
        - asset: fonts/Zain-Black.ttf
          weight: 900
        - asset: fonts/Zain-ExtraBold.ttf
          weight: 800
        - asset: fonts/Zain-Bold.ttf
          weight: 700
        - asset: fonts/Zain-Regular.ttf
          weight: 400
        - asset: fonts/Zain-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Zain-Light.ttf
          weight: 300
        - asset: fonts/Zain-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Zain-ExtraLight.ttf
          weight: 200

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: assets/icons/icon.png
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#3D0000"
  image: assets/icons/icon_splash.png

  android_12:
    color: "#3D0000"
    image: assets/icons/icon_splash.png
    icon_background_color: "#3D0000"